authors = ["emmett emmett@emmettboudreau.com"]
name = "Lathe"
uuid = "38d8eb38-e7b1-11e9-0012-376b6c802672"
version = "0.0.6"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
[compat]
julia = "1.0.3"
